# Generated by Django 3.2 on 2022-03-11 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_character_savingthrows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='savingThrows',
            field=models.JSONField(),
        ),
    ]
