# Generated by Django 3.2 on 2022-03-12 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_character_savingthrows'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='prof',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='skills',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='character',
            name='savingThrows',
            field=models.CharField(max_length=100),
        ),
    ]
